name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  linux:
    name: HLang - Linux - ${{ matrix.compiler }}
    runs-on: ubuntu-18.04
    container:
      image: buildpack-deps:focal
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      matrix:
        include:
          - compiler: ghc-9.0.1
            allow-failure: false
          - compiler: ghc-8.10.4
            allow-failure: false
          - compiler: ghc-8.8.4
            allow-failure: false
          - compiler: ghc-8.6.5
            allow-failure: false
          - compiler: ghc-8.4.4
            allow-failure: false
          - compiler: ghc-8.2.2
            allow-failure: false
      fail-fast: false
    steps:
      - name: apt
        run: |
          apt-get update
          apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git software-properties-common
          apt-add-repository -y 'ppa:hvr/ghc'
          apt-get update
          apt-get install -y $CC cabal-install-3.4
        env:
          CC: ${{ matrix.compiler }}
      - name: Set PATH and environment variables
        run: |
          echo "$HOME/.cabal/bin" >> $GITHUB_PATH
          echo "LANG=C.UTF-8" >> $GITHUB_ENV
          echo "CABAL_DIR=$HOME/.cabal" >> $GITHUB_ENV
          echo "CABAL_CONFIG=$HOME/.cabal/config" >> $GITHUB_ENV
          HCDIR=$(echo "/opt/$CC" | sed 's/-/\//')
          HCNAME=ghc
          HC=$HCDIR/bin/$HCNAME
          echo "HC=$HC" >> $GITHUB_ENV
          echo "HCPKG=$HCDIR/bin/$HCNAME-pkg" >> $GITHUB_ENV
          echo "HADDOCK=$HCDIR/bin/haddock" >> $GITHUB_ENV
          echo "CABAL=/opt/cabal/3.4/bin/cabal -vnormal+nowrap" >> $GITHUB_ENV
          HCNUMVER=$(${HC} --numeric-version|perl -ne '/^(\d+)\.(\d+)\.(\d+)(\.(\d+))?$/; print(10000 * $1 + 100 * $2 + ($3 == 0 ? $5 != 1 : $3))')
          echo "HCNUMVER=$HCNUMVER" >> $GITHUB_ENV
          echo "ARG_TESTS=--enable-tests" >> $GITHUB_ENV
          echo "ARG_BENCH=--enable-benchmarks" >> $GITHUB_ENV
          if [ $((HCNUMVER > 90001)) -ne 0 ] ; then echo "HEADHACKAGE=true" >> $GITHUB_ENV ; else echo "HEADHACKAGE=false" >> $GITHUB_ENV ; fi
          echo "ARG_COMPILER=--$HCNAME --with-compiler=$HC" >> $GITHUB_ENV
          echo "GHCJSARITH=0" >> $GITHUB_ENV
        env:
          CC: ${{ matrix.compiler }}
      - name: env
        run: |
          env
      - name: versions
        run: |
          $HC --version || true
          $HC --print-project-git-commit-id || true
          $CABAL --version || true
      - name: update cabal index
        run: |
          $CABAL v2-update -v
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: source
      - name: generate cabal.project
        run: |
          $CABAL v2-configure
      - name: install dependencies
        run: |
          $CABAL v2-build $ARG_COMPILER --disable-tests --disable-benchmarks --dependencies-only -j2 all
          $CABAL v2-build $ARG_COMPILER $ARG_TESTS $ARG_BENCH --dependencies-only -j2 all
      - name: build w/o tests
        run: |
          $CABAL v2-build $ARG_COMPILER --disable-tests --disable-benchmarks all
      - name: build
        run: |
          $CABAL v2-build $ARG_COMPILER $ARG_TESTS $ARG_BENCH all --write-ghc-environment-files=always
      - name: tests
        run: |
          $CABAL v2-test $ARG_COMPILER $ARG_TESTS $ARG_BENCH all --test-show-details=direct












